### ISSUE TITLE
Rebrand to Postlight Parser

### ISSUE THREAD

**Issue by scottwittrock** [postlight/slash-mercury-parser#4]
Remove any reference to "Mercury," which is the old brand. Replace with "Postlight Reader Parser" or "Parser" where applicable. Some of those tasks include: 
* Update the github repo name and readme
* Update the actual slash command to '/parse' instead of '/mercury'
* Review the project and update any other relevant references

**Comment by mfickanderson** [comment]
> Remove any reference to "Mercury," which is the old brand. Replace with "Postlight Reader Parser" or "Parser" where applicable. Some of those tasks include:
> 
> * Update the github repo name and readme
> * Update the actual slash command to '/parse' instead of '/mercury'
> * Review the project and update any other relevant references

Should the slash command on be `/parser` not `/parse`? just want to make sure that is correct
