### ISSUE TITLE
Update slack integration 

### ISSUE THREAD

**Issue by mfickanderson** [postlight/slash-mercury-parser#6]
Update slack integration to no longer be `mercury parser` 
 * include updating the actual slash command to '/parse' instead of '/mercury'

**Comment by JadTermsani** [comment]
- command is now `parser`

<img width="682" alt="Screen Shot 2023-02-02 at 9 18 43 PM" src="https://user-images.githubusercontent.com/32297675/216428747-ab3fd66b-8034-4ac1-bcbc-25a5378af8f8.png">

- App name is now Postlight Parser
<img width="736" alt="Screen Shot 2023-02-02 at 9 19 48 PM" src="https://user-images.githubusercontent.com/32297675/216428966-3f0b7866-80d3-484f-9315-a090c9842b79.png">
